$axure.loadCurrentPage({
  "url":"登录界面.html",
  "generationDate":new Date(1471517578784.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c22ecb29bcee419fbe7ee1e06209908a",
    "type":"Axure:Page",
    "name":"登录界面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a61c67a694804ae0bdbf0a24afd5dec8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCFF},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e2abd9a3c7a4defa04d4f813946e75c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u0.png"}},
{
          "id":"dd00640e60c9404b8c1052aa76afafc5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":30},
            "size":{
              "width":100,
              "height":100},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc968fd431c4f5eab5f1f01e80ed700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":30},
                "size":{
                  "width":100,
                  "height":100},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u2.png"}},
{
          "id":"fa7aa989b9384722adef4a3edbf88f13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":19,
              "y":160},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95e88676c27346aeac8e5e9769acacab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":160},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ce629ceeb6944c0bbbd035dc9742626",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":90,
              "y":160},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入账号"},
{
          "id":"5ba9e0cf421e41ae94c359ed07f9edeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":19,
              "y":220},
            "size":{
              "width":61,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e822ea17bb8b46479880ded3848c135d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":220},
                "size":{
                  "width":61,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0941c63216842faa8d624af27d8eae2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":90,
              "y":220},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入密码"},
{
          "id":"c2708714c890464e8b49f7cf508be6a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":19,
              "y":194},
            "size":{
              "width":275,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录界面/u10_line.png"}},
{
          "id":"7e01ef6367b34e15b25b189ba9b7389a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":15,
              "y":255},
            "size":{
              "width":275,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录界面/u10_line.png"}},
{
          "id":"b3b2c90221b840c8bb9818904e74b770",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":106.5,
              "y":315},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 轮播图",
                      "target":{
                        "targetType":"page",
                        "url":"轮播图.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "a61c67a694804ae0bdbf0a24afd5dec8":{
      "scriptId":"u0"},
    "4e2abd9a3c7a4defa04d4f813946e75c":{
      "scriptId":"u1"},
    "dd00640e60c9404b8c1052aa76afafc5":{
      "scriptId":"u2"},
    "4bc968fd431c4f5eab5f1f01e80ed700":{
      "scriptId":"u3"},
    "fa7aa989b9384722adef4a3edbf88f13":{
      "scriptId":"u4"},
    "95e88676c27346aeac8e5e9769acacab":{
      "scriptId":"u5"},
    "0ce629ceeb6944c0bbbd035dc9742626":{
      "scriptId":"u6"},
    "5ba9e0cf421e41ae94c359ed07f9edeb":{
      "scriptId":"u7"},
    "e822ea17bb8b46479880ded3848c135d":{
      "scriptId":"u8"},
    "c0941c63216842faa8d624af27d8eae2":{
      "scriptId":"u9"},
    "c2708714c890464e8b49f7cf508be6a8":{
      "scriptId":"u10"},
    "7e01ef6367b34e15b25b189ba9b7389a":{
      "scriptId":"u11"},
    "b3b2c90221b840c8bb9818904e74b770":{
      "scriptId":"u12"}}});