$axure.loadCurrentPage({
  "url":"登录界面验证.html",
  "generationDate":new Date(1471517578974.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"125d0b33b76c4a72a761691bfb75302b",
    "type":"Axure:Page",
    "name":"登录界面验证",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7113cc96ea0f4d0ea8ec89c6174cef94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCFF},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9873382a7bf946c887418a768b641ef8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u0.png"}},
{
          "id":"831a205fb0334161ab00cc3b51a7929e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":30},
            "size":{
              "width":100,
              "height":100},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d82deb370c2342d4a6c6b0487d22e90d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":30},
                "size":{
                  "width":100,
                  "height":100},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录界面/u2.png"}},
{
          "id":"b4f90ff5c511426d8e9af2a73bd76477",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":19,
              "y":160},
            "size":{
              "width":61,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9269f0d1f9c74575b109e49c72c70cdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":160},
                "size":{
                  "width":61,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44a7a159aedb4e6391bb52fba57d3416",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":90,
              "y":160},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入账号"},
{
          "id":"c98d2d21d09e4dc694075fcc638d0a55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":19,
              "y":220},
            "size":{
              "width":61,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88eeb293614f4e35af01f010889b3f01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":19,
                  "y":220},
                "size":{
                  "width":61,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee9372d0f9fc4e92b177ea1cb7c64bf6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":90,
              "y":220},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入密码"},
{
          "id":"5980199f472748e28588f4eb085a2140",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":19,
              "y":194},
            "size":{
              "width":275,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录界面/u10_line.png"}},
{
          "id":"f6b602d7512247abac8254c05d72d9b0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":15,
              "y":255},
            "size":{
              "width":275,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录界面/u10_line.png"}},
{
          "id":"63b17b8726db4f1a8c4d7cce891746a0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":106.5,
              "y":315},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 轮播图",
                      "target":{
                        "targetType":"page",
                        "url":"轮播图.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "7113cc96ea0f4d0ea8ec89c6174cef94":{
      "scriptId":"u0"},
    "9873382a7bf946c887418a768b641ef8":{
      "scriptId":"u1"},
    "831a205fb0334161ab00cc3b51a7929e":{
      "scriptId":"u2"},
    "d82deb370c2342d4a6c6b0487d22e90d":{
      "scriptId":"u3"},
    "b4f90ff5c511426d8e9af2a73bd76477":{
      "scriptId":"u4"},
    "9269f0d1f9c74575b109e49c72c70cdf":{
      "scriptId":"u5"},
    "44a7a159aedb4e6391bb52fba57d3416":{
      "scriptId":"u6"},
    "c98d2d21d09e4dc694075fcc638d0a55":{
      "scriptId":"u7"},
    "88eeb293614f4e35af01f010889b3f01":{
      "scriptId":"u8"},
    "ee9372d0f9fc4e92b177ea1cb7c64bf6":{
      "scriptId":"u9"},
    "5980199f472748e28588f4eb085a2140":{
      "scriptId":"u10"},
    "f6b602d7512247abac8254c05d72d9b0":{
      "scriptId":"u11"},
    "63b17b8726db4f1a8c4d7cce891746a0":{
      "scriptId":"u12"}}});