$axure.loadCurrentPage({
  "url":"轮播图.html",
  "generationDate":new Date(1471517578936.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f8c9d06e39ef42f1ac20e61509d0a9d9",
    "type":"Axure:Page",
    "name":"轮播图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"22dd94b3d574493e98ba80577f25daab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCFF},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c7963bf2fff4499b876337d74338020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCFF},
                "size":{
                  "width":320,
                  "height":568}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/轮播图/u0.png"}},
{
          "id":"073ca3d1887a4a6a88621b93a3ed8607",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":320,
              "height":200}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"16a9b9c2aac34ac09c75eebd49b3043d",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8945c65149d64c92b9013311eae89be3",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-10,
                      "y":0},
                    "size":{
                      "width":330,
                      "height":200}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0b5a2caf753244d0a3f5475e6e50f71f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-10,
                          "y":0},
                        "size":{
                          "width":330,
                          "height":200}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/轮播图/u3.jpg"}},
{
                  "id":"7e22969b8e0f46b69bf1dcc962e023a4",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":148},
                    "size":{
                      "width":20,
                      "height":20},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1d03c486ed2d414099ccd1aff2b7043e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":190,
                          "y":148},
                        "size":{
                          "width":20,
                          "height":20},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/轮播图/u5.png"}},
{
                  "id":"bb35ea86df084abb824488e056a09435",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":230,
                      "y":148},
                    "size":{
                      "width":20,
                      "height":20},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8239752cfae4145b29cddaeefd8ae3d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":230,
                          "y":148},
                        "size":{
                          "width":20,
                          "height":20},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/轮播图/u7.png"}},
{
                  "id":"6f48263b6a6149a991aa3d799d67f6a9",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":270,
                      "y":148},
                    "size":{
                      "width":20,
                      "height":20},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e1d2319cdf194fc8a639416de2714ce9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":270,
                          "y":148},
                        "size":{
                          "width":20,
                          "height":20},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/轮播图/u7.png"}},
{
                  "id":"78bd852cc7bf4f5e81f6fbd0c9b27575",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":40,
                      "y":140},
                    "size":{
                      "width":136,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15ce4156d66f48d9b28f261a314c2266",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":40,
                          "y":140},
                        "size":{
                          "width":136,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"0678469d64144b46ba280b7137e81779",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3a9e586bdeb948c7809c92b26e0baecd",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-20},
                    "size":{
                      "width":320,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e39e74fd0344b248d42150b3d7190ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-20},
                        "size":{
                          "width":320,
                          "height":220}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/轮播图/u13.jpg"}},
{
                  "id":"e9553420aae548cba8131129b7f7b417",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":190,
                      "y":148},
                    "size":{
                      "width":20,
                      "height":20},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fb3cf601e5d24689be7bd458069b55b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":190,
                          "y":148},
                        "size":{
                          "width":20,
                          "height":20},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/轮播图/u7.png"}},
{
                  "id":"1820e8bb35ae4757962b88d47e2f02ef",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":230,
                      "y":148},
                    "size":{
                      "width":20,
                      "height":20},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"94c42819515845fda8149ef0dcc62e7a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":230,
                          "y":148},
                        "size":{
                          "width":20,
                          "height":20},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/轮播图/u5.png"}},
{
                  "id":"6138dee5605e4988854d40b6d005b7dd",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":270,
                      "y":148},
                    "size":{
                      "width":20,
                      "height":20},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3d653392c92c46fbb0d36e5df79d1b18",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":270,
                          "y":148},
                        "size":{
                          "width":20,
                          "height":20},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/轮播图/u7.png"}},
{
                  "id":"f10a2f03ecdb4a8a8154fb61f1ca4b2b",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":140},
                    "size":{
                      "width":121,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3ddf00a713ab4020bde42bcaea659d8c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":140},
                        "size":{
                          "width":121,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"039aa25b3ef7411597451de0949c0ebd",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"091bd3c1a10c4ea89e364869b7032e3a",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":200}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a03ac17457d048a7806d163e2234379f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":200}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/轮播图/u23.jpg"}},
{
                  "id":"74fe9287b6b149949f859af5b930a721",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":210,
                      "y":152},
                    "size":{
                      "width":20,
                      "height":20},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b8c010833a984989bbacd25d13887446",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":210,
                          "y":152},
                        "size":{
                          "width":20,
                          "height":20},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/轮播图/u7.png"}},
{
                  "id":"ba8f16eac5b842f98b3291e725226fe6",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "location":{
                      "x":250,
                      "y":152},
                    "size":{
                      "width":20,
                      "height":20},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a49c52c47a6445d598f88da59dafaba6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "location":{
                          "x":250,
                          "y":152},
                        "size":{
                          "width":20,
                          "height":20},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/轮播图/u7.png"}},
{
                  "id":"2d7081237f4a4ce8a90a8d115ae8d80b",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":290,
                      "y":152},
                    "size":{
                      "width":20,
                      "height":20},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f41b849de146472cba3be6ed0c46158b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":290,
                          "y":152},
                        "size":{
                          "width":20,
                          "height":20},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/轮播图/u5.png"}},
{
                  "id":"0ea8d276b7964c1cb50a82b9fac06a23",
                  "label":"",
                  "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":50,
                      "y":144},
                    "size":{
                      "width":121,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4d87db35066b4aa2b31961539817364d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"073ca3d1887a4a6a88621b93a3ed8607",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":50,
                          "y":144},
                        "size":{
                          "width":121,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"639568ba58644715ad4b10ee7a90225e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d71ad3876d5e42b8886d71b03307a429",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) to 下一步 向左滑动 out 500ms 向左滑动 in 500ms wrap repeat every 2000 ms",
                      "panelsToStates":[{
                          "panelPath":["073ca3d1887a4a6a88621b93a3ed8607"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":2000,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/轮播图/u33.png"}},
{
          "id":"3c4e364a06944c8c988b426f7254a152",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":70},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dab26e69d93e4effb59cbffc94b3d648",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":290,
                  "y":70},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]},
{
                      "action":"setPanelState",
                      "description":"设置 (动态面板) to 下一步 向左滑动 out 500ms 向左滑动 in 500ms wrap repeat every 2000 ms",
                      "panelsToStates":[{
                          "panelPath":["073ca3d1887a4a6a88621b93a3ed8607"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":2000,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/轮播图/u35.png"}},
{
          "id":"6227c81f6613457789a09bbbfda4389a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":0,
              "y":200},
            "size":{
              "width":320,
              "height":368}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57fffc90304e431fb9e4ebf41a12a040",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":0,
                  "y":200},
                "size":{
                  "width":320,
                  "height":368}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/轮播图/u37.png"}},
{
          "id":"b0990b972f734a9a86dc075ddf60d4a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF99CCFF},
            "location":{
              "x":80,
              "y":230},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a692a75d8d5f4b138f8fd91d513703ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CCFF},
                "location":{
                  "x":80,
                  "y":230},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/轮播图/u39.png"}},
{
          "id":"1bfac2826bbc4c02ae821faa1cf52a13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF99CCFF},
            "location":{
              "x":200,
              "y":230},
            "size":{
              "width":97,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa0ddb9fce154e6f9b4065be3bfed957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF99CCFF},
                "location":{
                  "x":200,
                  "y":230},
                "size":{
                  "width":97,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/轮播图/u41.png"}},
{
          "id":"6336928df30941289bb37a8423d163fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":235},
            "size":{
              "width":19,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3519f615858842fda624a8e070a097a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":235},
                "size":{
                  "width":19,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/轮播图/u43.jpg"}},
{
          "id":"ad1081e1214343a999527a21ae371eea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":207,
              "y":235},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"708b5c3db864487cba355ff3492285e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":207,
                  "y":235},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/轮播图/u45.jpg"}},
{
          "id":"1df750b573cd491ba618d0ef866d7022",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":300},
            "size":{
              "width":300,
              "height":200}},
          "adaptiveStyles":{
}},
{
          "id":"885a3ff4ea16407a93cf1aa1ad414d27",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":210},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f752884c37a44996a803b534490d8906",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":210},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/轮播图/u48.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "22dd94b3d574493e98ba80577f25daab":{
      "scriptId":"u0"},
    "5c7963bf2fff4499b876337d74338020":{
      "scriptId":"u1"},
    "073ca3d1887a4a6a88621b93a3ed8607":{
      "scriptId":"u2"},
    "8945c65149d64c92b9013311eae89be3":{
      "scriptId":"u3"},
    "0b5a2caf753244d0a3f5475e6e50f71f":{
      "scriptId":"u4"},
    "7e22969b8e0f46b69bf1dcc962e023a4":{
      "scriptId":"u5"},
    "1d03c486ed2d414099ccd1aff2b7043e":{
      "scriptId":"u6"},
    "bb35ea86df084abb824488e056a09435":{
      "scriptId":"u7"},
    "a8239752cfae4145b29cddaeefd8ae3d":{
      "scriptId":"u8"},
    "6f48263b6a6149a991aa3d799d67f6a9":{
      "scriptId":"u9"},
    "e1d2319cdf194fc8a639416de2714ce9":{
      "scriptId":"u10"},
    "78bd852cc7bf4f5e81f6fbd0c9b27575":{
      "scriptId":"u11"},
    "15ce4156d66f48d9b28f261a314c2266":{
      "scriptId":"u12"},
    "3a9e586bdeb948c7809c92b26e0baecd":{
      "scriptId":"u13"},
    "2e39e74fd0344b248d42150b3d7190ee":{
      "scriptId":"u14"},
    "e9553420aae548cba8131129b7f7b417":{
      "scriptId":"u15"},
    "fb3cf601e5d24689be7bd458069b55b1":{
      "scriptId":"u16"},
    "1820e8bb35ae4757962b88d47e2f02ef":{
      "scriptId":"u17"},
    "94c42819515845fda8149ef0dcc62e7a":{
      "scriptId":"u18"},
    "6138dee5605e4988854d40b6d005b7dd":{
      "scriptId":"u19"},
    "3d653392c92c46fbb0d36e5df79d1b18":{
      "scriptId":"u20"},
    "f10a2f03ecdb4a8a8154fb61f1ca4b2b":{
      "scriptId":"u21"},
    "3ddf00a713ab4020bde42bcaea659d8c":{
      "scriptId":"u22"},
    "091bd3c1a10c4ea89e364869b7032e3a":{
      "scriptId":"u23"},
    "a03ac17457d048a7806d163e2234379f":{
      "scriptId":"u24"},
    "74fe9287b6b149949f859af5b930a721":{
      "scriptId":"u25"},
    "b8c010833a984989bbacd25d13887446":{
      "scriptId":"u26"},
    "ba8f16eac5b842f98b3291e725226fe6":{
      "scriptId":"u27"},
    "a49c52c47a6445d598f88da59dafaba6":{
      "scriptId":"u28"},
    "2d7081237f4a4ce8a90a8d115ae8d80b":{
      "scriptId":"u29"},
    "f41b849de146472cba3be6ed0c46158b":{
      "scriptId":"u30"},
    "0ea8d276b7964c1cb50a82b9fac06a23":{
      "scriptId":"u31"},
    "4d87db35066b4aa2b31961539817364d":{
      "scriptId":"u32"},
    "639568ba58644715ad4b10ee7a90225e":{
      "scriptId":"u33"},
    "d71ad3876d5e42b8886d71b03307a429":{
      "scriptId":"u34"},
    "3c4e364a06944c8c988b426f7254a152":{
      "scriptId":"u35"},
    "dab26e69d93e4effb59cbffc94b3d648":{
      "scriptId":"u36"},
    "6227c81f6613457789a09bbbfda4389a":{
      "scriptId":"u37"},
    "57fffc90304e431fb9e4ebf41a12a040":{
      "scriptId":"u38"},
    "b0990b972f734a9a86dc075ddf60d4a9":{
      "scriptId":"u39"},
    "a692a75d8d5f4b138f8fd91d513703ed":{
      "scriptId":"u40"},
    "1bfac2826bbc4c02ae821faa1cf52a13":{
      "scriptId":"u41"},
    "fa0ddb9fce154e6f9b4065be3bfed957":{
      "scriptId":"u42"},
    "6336928df30941289bb37a8423d163fc":{
      "scriptId":"u43"},
    "3519f615858842fda624a8e070a097a1":{
      "scriptId":"u44"},
    "ad1081e1214343a999527a21ae371eea":{
      "scriptId":"u45"},
    "708b5c3db864487cba355ff3492285e6":{
      "scriptId":"u46"},
    "1df750b573cd491ba618d0ef866d7022":{
      "scriptId":"u47"},
    "885a3ff4ea16407a93cf1aa1ad414d27":{
      "scriptId":"u48"},
    "f752884c37a44996a803b534490d8906":{
      "scriptId":"u49"}}});